sky:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: sky_take_out
    username: postgres
    password: '@Asfhuk554163'
